/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AreaId = IDL.Nat;
export const Area = IDL.Record({
  'latitude' : IDL.Float64,
  'area_name' : IDL.Text,
  'longitude' : IDL.Float64,
  'area_id' : AreaId,
  'population' : IDL.Nat,
});
export const LeakId = IDL.Nat;
export const PipeId = IDL.Nat;
export const LeakIncident = IDL.Record({
  'resolved_status' : IDL.Bool,
  'latitude' : IDL.Float64,
  'leak_id' : LeakId,
  'leak_severity' : IDL.Text,
  'longitude' : IDL.Float64,
  'area_id' : AreaId,
  'pipe_id' : PipeId,
  'reported_time' : IDL.Text,
});
export const ReadingId = IDL.Nat;
export const MeterReading = IDL.Record({
  'reading_id' : ReadingId,
  'meter_id' : IDL.Text,
  'area_id' : AreaId,
  'reading_date' : IDL.Text,
  'reading_value' : IDL.Float64,
});
export const PipeNetwork = IDL.Record({
  'status' : IDL.Text,
  'start_lat' : IDL.Float64,
  'start_lng' : IDL.Float64,
  'diameter' : IDL.Float64,
  'end_lat' : IDL.Float64,
  'end_lng' : IDL.Float64,
  'pipe_id' : PipeId,
});
export const PressureId = IDL.Nat;
export const PressureLog = IDL.Record({
  'pressure_id' : PressureId,
  'recorded_at' : IDL.Text,
  'pressure_value' : IDL.Float64,
  'pipe_id' : PipeId,
});
export const ReportId = IDL.Nat;
export const DailyReport = IDL.Record({
  'report_id' : ReportId,
  'reading_count' : IDL.Nat,
  'generated_at' : IDL.Text,
  'report_date' : IDL.Text,
  'total_usage' : IDL.Float64,
  'area_id' : AreaId,
});
export const DashboardStats = IDL.Record({
  'today_usage' : IDL.Float64,
  'avg_pressure' : IDL.Float64,
  'active_leaks' : IDL.Nat,
  'shortage_risk' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addArea' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
      [Area],
      [],
    ),
  'addLeakIncident' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Float64,
        IDL.Float64,
      ],
      [LeakIncident],
      [],
    ),
  'addMeterReading' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
      [MeterReading],
      [],
    ),
  'addPipe' : IDL.Func(
      [
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [PipeNetwork],
      [],
    ),
  'addPressureLog' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text],
      [PressureLog],
      [],
    ),
  'deleteArea' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLeakIncident' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMeterReading' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePipe' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePressureLog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAreas' : IDL.Func([], [IDL.Vec(Area)], ['query']),
  'getDailyReports' : IDL.Func([], [IDL.Vec(DailyReport)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getLeakIncidents' : IDL.Func([], [IDL.Vec(LeakIncident)], ['query']),
  'getMeterReadings' : IDL.Func([], [IDL.Vec(MeterReading)], ['query']),
  'getMeterReadingsByArea' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MeterReading)],
      ['query'],
    ),
  'getPipes' : IDL.Func([], [IDL.Vec(PipeNetwork)], ['query']),
  'getPressureLogs' : IDL.Func([], [IDL.Vec(PressureLog)], ['query']),
  'getPressureLogsByPipe' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PressureLog)],
      ['query'],
    ),
  'runDailyAggregation' : IDL.Func([], [IDL.Nat], []),
  'toggleLeakResolved' : IDL.Func([IDL.Nat], [IDL.Opt(LeakIncident)], []),
  'updateArea' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
      [IDL.Opt(Area)],
      [],
    ),
  'updateLeakIncident' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Opt(LeakIncident)],
      [],
    ),
  'updateMeterReading' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
      [IDL.Opt(MeterReading)],
      [],
    ),
  'updatePipe' : IDL.Func(
      [
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Opt(PipeNetwork)],
      [],
    ),
  'updatePressureLog' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text],
      [IDL.Opt(PressureLog)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AreaId = IDL.Nat;
  const Area = IDL.Record({
    'latitude' : IDL.Float64,
    'area_name' : IDL.Text,
    'longitude' : IDL.Float64,
    'area_id' : AreaId,
    'population' : IDL.Nat,
  });
  const LeakId = IDL.Nat;
  const PipeId = IDL.Nat;
  const LeakIncident = IDL.Record({
    'resolved_status' : IDL.Bool,
    'latitude' : IDL.Float64,
    'leak_id' : LeakId,
    'leak_severity' : IDL.Text,
    'longitude' : IDL.Float64,
    'area_id' : AreaId,
    'pipe_id' : PipeId,
    'reported_time' : IDL.Text,
  });
  const ReadingId = IDL.Nat;
  const MeterReading = IDL.Record({
    'reading_id' : ReadingId,
    'meter_id' : IDL.Text,
    'area_id' : AreaId,
    'reading_date' : IDL.Text,
    'reading_value' : IDL.Float64,
  });
  const PipeNetwork = IDL.Record({
    'status' : IDL.Text,
    'start_lat' : IDL.Float64,
    'start_lng' : IDL.Float64,
    'diameter' : IDL.Float64,
    'end_lat' : IDL.Float64,
    'end_lng' : IDL.Float64,
    'pipe_id' : PipeId,
  });
  const PressureId = IDL.Nat;
  const PressureLog = IDL.Record({
    'pressure_id' : PressureId,
    'recorded_at' : IDL.Text,
    'pressure_value' : IDL.Float64,
    'pipe_id' : PipeId,
  });
  const ReportId = IDL.Nat;
  const DailyReport = IDL.Record({
    'report_id' : ReportId,
    'reading_count' : IDL.Nat,
    'generated_at' : IDL.Text,
    'report_date' : IDL.Text,
    'total_usage' : IDL.Float64,
    'area_id' : AreaId,
  });
  const DashboardStats = IDL.Record({
    'today_usage' : IDL.Float64,
    'avg_pressure' : IDL.Float64,
    'active_leaks' : IDL.Nat,
    'shortage_risk' : IDL.Bool,
  });
  
  return IDL.Service({
    'addArea' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
        [Area],
        [],
      ),
    'addLeakIncident' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Float64,
          IDL.Float64,
        ],
        [LeakIncident],
        [],
      ),
    'addMeterReading' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
        [MeterReading],
        [],
      ),
    'addPipe' : IDL.Func(
        [
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [PipeNetwork],
        [],
      ),
    'addPressureLog' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text],
        [PressureLog],
        [],
      ),
    'deleteArea' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLeakIncident' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMeterReading' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePipe' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePressureLog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAreas' : IDL.Func([], [IDL.Vec(Area)], ['query']),
    'getDailyReports' : IDL.Func([], [IDL.Vec(DailyReport)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getLeakIncidents' : IDL.Func([], [IDL.Vec(LeakIncident)], ['query']),
    'getMeterReadings' : IDL.Func([], [IDL.Vec(MeterReading)], ['query']),
    'getMeterReadingsByArea' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MeterReading)],
        ['query'],
      ),
    'getPipes' : IDL.Func([], [IDL.Vec(PipeNetwork)], ['query']),
    'getPressureLogs' : IDL.Func([], [IDL.Vec(PressureLog)], ['query']),
    'getPressureLogsByPipe' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PressureLog)],
        ['query'],
      ),
    'runDailyAggregation' : IDL.Func([], [IDL.Nat], []),
    'toggleLeakResolved' : IDL.Func([IDL.Nat], [IDL.Opt(LeakIncident)], []),
    'updateArea' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
        [IDL.Opt(Area)],
        [],
      ),
    'updateLeakIncident' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Opt(LeakIncident)],
        [],
      ),
    'updateMeterReading' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Opt(MeterReading)],
        [],
      ),
    'updatePipe' : IDL.Func(
        [
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Opt(PipeNetwork)],
        [],
      ),
    'updatePressureLog' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Opt(PressureLog)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };