/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Area {
  'latitude' : number,
  'area_name' : string,
  'longitude' : number,
  'area_id' : AreaId,
  'population' : bigint,
}
export type AreaId = bigint;
export interface DailyReport {
  'report_id' : ReportId,
  'reading_count' : bigint,
  'generated_at' : string,
  'report_date' : string,
  'total_usage' : number,
  'area_id' : AreaId,
}
export interface DashboardStats {
  'today_usage' : number,
  'avg_pressure' : number,
  'active_leaks' : bigint,
  'shortage_risk' : boolean,
}
export type LeakId = bigint;
export interface LeakIncident {
  'resolved_status' : boolean,
  'latitude' : number,
  'leak_id' : LeakId,
  'leak_severity' : string,
  'longitude' : number,
  'area_id' : AreaId,
  'pipe_id' : PipeId,
  'reported_time' : string,
}
export interface MeterReading {
  'reading_id' : ReadingId,
  'meter_id' : string,
  'area_id' : AreaId,
  'reading_date' : string,
  'reading_value' : number,
}
export type PipeId = bigint;
export interface PipeNetwork {
  'status' : string,
  'start_lat' : number,
  'start_lng' : number,
  'diameter' : number,
  'end_lat' : number,
  'end_lng' : number,
  'pipe_id' : PipeId,
}
export type PressureId = bigint;
export interface PressureLog {
  'pressure_id' : PressureId,
  'recorded_at' : string,
  'pressure_value' : number,
  'pipe_id' : PipeId,
}
export type ReadingId = bigint;
export type ReportId = bigint;
export interface _SERVICE {
  'addArea' : ActorMethod<[string, bigint, number, number], Area>,
  'addLeakIncident' : ActorMethod<
    [bigint, bigint, string, string, boolean, number, number],
    LeakIncident
  >,
  'addMeterReading' : ActorMethod<
    [string, bigint, number, string],
    MeterReading
  >,
  'addPipe' : ActorMethod<
    [number, number, number, number, number, string],
    PipeNetwork
  >,
  'addPressureLog' : ActorMethod<[bigint, number, string], PressureLog>,
  'deleteArea' : ActorMethod<[bigint], boolean>,
  'deleteLeakIncident' : ActorMethod<[bigint], boolean>,
  'deleteMeterReading' : ActorMethod<[bigint], boolean>,
  'deletePipe' : ActorMethod<[bigint], boolean>,
  'deletePressureLog' : ActorMethod<[bigint], boolean>,
  'getAreas' : ActorMethod<[], Array<Area>>,
  'getDailyReports' : ActorMethod<[], Array<DailyReport>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getLeakIncidents' : ActorMethod<[], Array<LeakIncident>>,
  'getMeterReadings' : ActorMethod<[], Array<MeterReading>>,
  'getMeterReadingsByArea' : ActorMethod<[bigint], Array<MeterReading>>,
  'getPipes' : ActorMethod<[], Array<PipeNetwork>>,
  'getPressureLogs' : ActorMethod<[], Array<PressureLog>>,
  'getPressureLogsByPipe' : ActorMethod<[bigint], Array<PressureLog>>,
  'runDailyAggregation' : ActorMethod<[], bigint>,
  'toggleLeakResolved' : ActorMethod<[bigint], [] | [LeakIncident]>,
  'updateArea' : ActorMethod<
    [bigint, string, bigint, number, number],
    [] | [Area]
  >,
  'updateLeakIncident' : ActorMethod<
    [bigint, bigint, bigint, string, string, boolean, number, number],
    [] | [LeakIncident]
  >,
  'updateMeterReading' : ActorMethod<
    [bigint, string, bigint, number, string],
    [] | [MeterReading]
  >,
  'updatePipe' : ActorMethod<
    [bigint, number, number, number, number, number, string],
    [] | [PipeNetwork]
  >,
  'updatePressureLog' : ActorMethod<
    [bigint, bigint, number, string],
    [] | [PressureLog]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];