/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DashboardStats {
    today_usage: number;
    avg_pressure: number;
    active_leaks: bigint;
    shortage_risk: boolean;
}
export type ReportId = bigint;
export type LeakId = bigint;
export interface Area {
    latitude: number;
    area_name: string;
    longitude: number;
    area_id: AreaId;
    population: bigint;
}
export interface PipeNetwork {
    status: string;
    start_lat: number;
    start_lng: number;
    diameter: number;
    end_lat: number;
    end_lng: number;
    pipe_id: PipeId;
}
export type PressureId = bigint;
export interface MeterReading {
    reading_id: ReadingId;
    meter_id: string;
    area_id: AreaId;
    reading_date: string;
    reading_value: number;
}
export interface LeakIncident {
    resolved_status: boolean;
    latitude: number;
    leak_id: LeakId;
    leak_severity: string;
    longitude: number;
    area_id: AreaId;
    pipe_id: PipeId;
    reported_time: string;
}
export interface DailyReport {
    report_id: ReportId;
    reading_count: bigint;
    generated_at: string;
    report_date: string;
    total_usage: number;
    area_id: AreaId;
}
export type AreaId = bigint;
export type PipeId = bigint;
export type ReadingId = bigint;
export interface PressureLog {
    pressure_id: PressureId;
    recorded_at: string;
    pressure_value: number;
    pipe_id: PipeId;
}
export interface backendInterface {
    addArea(name: string, population: bigint, lat: number, lng: number): Promise<Area>;
    addLeakIncident(pipe_id: bigint, area_id: bigint, severity: string, reported_time: string, resolved: boolean, lat: number, lng: number): Promise<LeakIncident>;
    addMeterReading(meter_id: string, area_id: bigint, value: number, date: string): Promise<MeterReading>;
    addPipe(start_lat: number, start_lng: number, end_lat: number, end_lng: number, diameter: number, status: string): Promise<PipeNetwork>;
    addPressureLog(pipe_id: bigint, value: number, recorded_at: string): Promise<PressureLog>;
    deleteArea(id: bigint): Promise<boolean>;
    deleteLeakIncident(id: bigint): Promise<boolean>;
    deleteMeterReading(id: bigint): Promise<boolean>;
    deletePipe(id: bigint): Promise<boolean>;
    deletePressureLog(id: bigint): Promise<boolean>;
    getAreas(): Promise<Array<Area>>;
    getDailyReports(): Promise<Array<DailyReport>>;
    getDashboardStats(): Promise<DashboardStats>;
    getLeakIncidents(): Promise<Array<LeakIncident>>;
    getMeterReadings(): Promise<Array<MeterReading>>;
    getMeterReadingsByArea(area_id: bigint): Promise<Array<MeterReading>>;
    getPipes(): Promise<Array<PipeNetwork>>;
    getPressureLogs(): Promise<Array<PressureLog>>;
    getPressureLogsByPipe(pipe_id: bigint): Promise<Array<PressureLog>>;
    runDailyAggregation(): Promise<bigint>;
    toggleLeakResolved(id: bigint): Promise<LeakIncident | null>;
    updateArea(id: bigint, name: string, population: bigint, lat: number, lng: number): Promise<Area | null>;
    updateLeakIncident(id: bigint, pipe_id: bigint, area_id: bigint, severity: string, reported_time: string, resolved: boolean, lat: number, lng: number): Promise<LeakIncident | null>;
    updateMeterReading(id: bigint, meter_id: string, area_id: bigint, value: number, date: string): Promise<MeterReading | null>;
    updatePipe(id: bigint, start_lat: number, start_lng: number, end_lat: number, end_lng: number, diameter: number, status: string): Promise<PipeNetwork | null>;
    updatePressureLog(id: bigint, pipe_id: bigint, value: number, recorded_at: string): Promise<PressureLog | null>;
}
import type { Area as _Area, LeakIncident as _LeakIncident, MeterReading as _MeterReading, PipeNetwork as _PipeNetwork, PressureLog as _PressureLog } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addArea(arg0: string, arg1: bigint, arg2: number, arg3: number): Promise<Area> {
        if (this.processError) {
            try {
                const result = await this.actor.addArea(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addArea(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addLeakIncident(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: boolean, arg5: number, arg6: number): Promise<LeakIncident> {
        if (this.processError) {
            try {
                const result = await this.actor.addLeakIncident(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLeakIncident(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addMeterReading(arg0: string, arg1: bigint, arg2: number, arg3: string): Promise<MeterReading> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeterReading(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeterReading(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addPipe(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: string): Promise<PipeNetwork> {
        if (this.processError) {
            try {
                const result = await this.actor.addPipe(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPipe(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addPressureLog(arg0: bigint, arg1: number, arg2: string): Promise<PressureLog> {
        if (this.processError) {
            try {
                const result = await this.actor.addPressureLog(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPressureLog(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteArea(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArea(arg0);
            return result;
        }
    }
    async deleteLeakIncident(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLeakIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLeakIncident(arg0);
            return result;
        }
    }
    async deleteMeterReading(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeterReading(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeterReading(arg0);
            return result;
        }
    }
    async deletePipe(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePipe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePipe(arg0);
            return result;
        }
    }
    async deletePressureLog(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePressureLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePressureLog(arg0);
            return result;
        }
    }
    async getAreas(): Promise<Array<Area>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAreas();
            return result;
        }
    }
    async getDailyReports(): Promise<Array<DailyReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyReports();
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getLeakIncidents(): Promise<Array<LeakIncident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeakIncidents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeakIncidents();
            return result;
        }
    }
    async getMeterReadings(): Promise<Array<MeterReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeterReadings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeterReadings();
            return result;
        }
    }
    async getMeterReadingsByArea(arg0: bigint): Promise<Array<MeterReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeterReadingsByArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeterReadingsByArea(arg0);
            return result;
        }
    }
    async getPipes(): Promise<Array<PipeNetwork>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPipes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPipes();
            return result;
        }
    }
    async getPressureLogs(): Promise<Array<PressureLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPressureLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPressureLogs();
            return result;
        }
    }
    async getPressureLogsByPipe(arg0: bigint): Promise<Array<PressureLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPressureLogsByPipe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPressureLogsByPipe(arg0);
            return result;
        }
    }
    async runDailyAggregation(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.runDailyAggregation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runDailyAggregation();
            return result;
        }
    }
    async toggleLeakResolved(arg0: bigint): Promise<LeakIncident | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLeakResolved(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLeakResolved(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateArea(arg0: bigint, arg1: string, arg2: bigint, arg3: number, arg4: number): Promise<Area | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArea(arg0, arg1, arg2, arg3, arg4);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArea(arg0, arg1, arg2, arg3, arg4);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLeakIncident(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: boolean, arg6: number, arg7: number): Promise<LeakIncident | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeakIncident(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeakIncident(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMeterReading(arg0: bigint, arg1: string, arg2: bigint, arg3: number, arg4: string): Promise<MeterReading | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMeterReading(arg0, arg1, arg2, arg3, arg4);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMeterReading(arg0, arg1, arg2, arg3, arg4);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePipe(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: string): Promise<PipeNetwork | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePipe(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePipe(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePressureLog(arg0: bigint, arg1: bigint, arg2: number, arg3: string): Promise<PressureLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePressureLog(arg0, arg1, arg2, arg3);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePressureLog(arg0, arg1, arg2, arg3);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeakIncident]): LeakIncident | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Area]): Area | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MeterReading]): MeterReading | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PipeNetwork]): PipeNetwork | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PressureLog]): PressureLog | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
